In [4]:
#data types
#integers 0-9
#special characters */-+%$#&@^*()!
#strings a-z

#list [1,2,3,4,5,6,7,7,]
#dict {Satish:18,Om:18,Rudra:18}
#tuple(1,2,3,4,5,6,7,8,9,9,9)




(1, 2, 43, 55, 55)


In [2]:
a=153
b=str(a)
result=int(b[0])
print(result)

1


In [1]:
sum=0
for i in range(0,101):
    sum=sum+i
print(sum)

5050


In [11]:
s=0
for j in range(0,101):
    if j%2!=0:
        s=s+j
print(s)

2500


In [9]:
2%2

0

In [8]:
#variables
age=int()
print()


18


In [10]:
#literal
"rudra","True" #string literal
1254 #numeric/integer literal
True/False   #boolean literal
13.25 #floating Point literal



100
100


In [21]:
a=100
A=100
a=100
a=55
print(a)

55


In [5]:
x=True
y=False
z=False
print(x or y and z)

True


In [6]:
print("hello world")
print("hell
print("Hello")

SyntaxError: unterminated string literal (detected at line 2) (1297692345.py, line 2)

In [ ]:
what is boolean?
True, False

In [23]:
>120

SyntaxError: invalid syntax (3635790229.py, line 1)

In [2]:
import numpy as np
ari=np.arange(1,2,0.1,dtype=float)
b=np.zeros_like(ari)



array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [ ]:
Arithmetic opr
+-/*%//** 
#bitwise opr
& and operator
^ XOR
|  or

In [4]:
import numpy as np
arr=np.arange(10)
print(arr[1:6])
print(arr[1:6:2])
print(arr[-6:-1])

[1 2 3 4 5]
[1 3 5]
[4 5 6 7 8]


In [4]:
import numpy as np
arr=np.array([0,1,2,3,4,5,6,7,8,9])
a=arr.resize(2,3)
print(a)

None


In [26]:
<
>
<=
>=
!=
==

<>:1: SyntaxWarning: "is not" with a literal. Did you mean "!="?
<>:1: SyntaxWarning: "is not" with a literal. Did you mean "!="?
C:\Users\Rudra\AppData\Local\Temp\ipykernel_19028\2296977833.py:1: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  "Rudra" is not "RudRa"


True

In [29]:
a=100
a=a+1 a//=1

print(a)

101


In [38]:
#membership opr
" " not in "RudraKashyap"

True

In [43]:
#logical operators
("r" and "k") in ("Rudra Kashyap")

False

In [1]:
a=100
print(a)

100


In [11]:
a=10
b=20
c=a+b
print("Thesum of two number is",c)

Thesum of two number is 30


In [2]:
a=input()
type(a)

str

In [5]:
a=[1,2,3,4]
print("The data type is: ",type(a))

The data type is:  <class 'list'>


In [11]:
a="100"
print(a)
a=int(a)
type(a)

100


int

In [3]:
import turtle
dir(turtle)

['Canvas',
 'Pen',
 'RawPen',
 'RawTurtle',
 'Screen',
 'ScrolledCanvas',
 'Shape',
 'TK',
 'TNavigator',
 'TPen',
 'Tbuffer',
 'Terminator',
 'Turtle',
 'TurtleGraphicsError',
 'TurtleScreen',
 'TurtleScreenBase',
 'Vec2D',
 '_CFG',
 '_LANGUAGE',
 '_Root',
 '_Screen',
 '_TurtleImage',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__forwardmethods',
 '__func_body',
 '__loader__',
 '__methodDict',
 '__methods',
 '__name__',
 '__package__',
 '__spec__',
 '__stringBody',
 '_alias_list',
 '_make_global_funcs',
 '_screen_docrevise',
 '_tg_classes',
 '_tg_screen_functions',
 '_tg_turtle_functions',
 '_tg_utilities',
 '_turtle_docrevise',
 '_ver',
 'addshape',
 'back',
 'backward',
 'begin_fill',
 'begin_poly',
 'bgcolor',
 'bgpic',
 'bk',
 'bye',
 'circle',
 'clear',
 'clearscreen',
 'clearstamp',
 'clearstamps',
 'clone',
 'color',
 'colormode',
 'config_dict',
 'deepcopy',
 'degrees',
 'delay',
 'distance',
 'done',
 'dot',
 'down',
 'end_fill',
 'end_poly',
 'exit

In [14]:
a=int(input("Enter a number: "))
type(a)

int

In [ ]:
int()#it is used to convert string numbers to integer

In [15]:
a=100
a=str(a)
type(a)

str

In [ ]:
def adding():
    a=int(input())
    b=int(input())
    c=a+b
    print(c)
adding()

In [1]:
"R".isupper()

True

In [3]:
import bank
bank.menu()


    
    1) Account Details
    
    2) Transaction
    
    3) Transaction Details
    
    4) Balance
    
    5) Delete Account
    
    6) Feedback
    
    7) Logout
    
    8) Back
    
    


In [3]:
l1=[1,2,3,4,5,6,7]
i=0
while True:
    print(l1[i])
    i+=1
    if len(l1)==i:
        False
        break


1
2
3
4
5
6
7


In [1]:
num=len(input("Enter your name: "))
print(num)

5


In [1]:
l1=[]
n=int(input("Enter how many elemts you want in your list:  "))
for i in range(n):
    e=int(input("Enter the elemnt"))
    l1.append(e)
print("Your list is: ",l1)

Your list is:  [45, 25]


In [1]:
m="I LOVE PYTHON"
count=0
for i in m:
    if i=="O":
        continue
    else:
        count+=1
print(count)

11


In [6]:
i=1
for x in range(1,4):
    for y in range(1,3):
        i=i+(i*1)
print(i)

2
4
8
16
32
64
64


In [2]:
print(3*3+3/3-3)

7.0


In [11]:
n=int(input())
for i in range(n):
    l1=[]
    x, y, z = input().split()
    l1.append(int(x))
    l1.append(int(y))
    l1.append(int(z))
    l1.remove(max(l1))
    print(max(l1))

10
56


In [ ]:
n=int(input())
for i in range(n):
    N, M = input().split()
    friends_sho=N*2
    no_s=friends_sho-M
    print(no_s)

In [ ]:
n=int(input())
for i in range(n):
    N, M = input().split()
    r_s=int(N)
    if int(M)>int(N) or int(M)<int(N):
        M=int(N)
        print(M)
    else:
        print(M)

In [ ]:
T=int(input())
for i in range(T):
    N, X = input().split()
    if int(X)%int(N)==0:
        print("YES")
    else:
        print("NO")
        

In [11]:
A=input().split()
print(A)

['1', '2', '3']


In [20]:
T=int(input())
for i in range(T):
    N=int(input())
    A=input().split()
    if len(A)==N:
        d={}
        for x in A:
            d[x]=d.get(x,0)+1
        a=max(d.values())
        l=[]
        for i, j in d.items():
            if j==a:
                l.append(i)
        if len(l)>1:
            print("CONFUSED")
        else:
            print(i)


CONFUSED


In [26]:
T=int(input())
for i in range(T):
    N=int(input())
    A=input().split()
    if len(A)==N:
        d={}
        for x in A:
            d[x]=d.get(x,0)+1
        a=max(d.values())
        l=[]
        for i, j in d.items():
            if j==a:
                l.append(i)
                print(i)
        if len(l)>1:
            print("CONFUSED")
        else:
            print(l[0])

4
4


In [6]:
100//20

5

In [ ]:
T=int(input())
for i in range(T):
    X, Y= input().split()
    print(int(X)//(int(Y)*2))

In [9]:
5%0

ZeroDivisionError: integer modulo by zero

In [13]:
0%5

0

In [17]:
21//10

2

In [20]:
10//4

2

In [17]:
9//4

2

In [20]:
8%4

0

In [54]:
#bubble sort
l1=[10,15,4,23,0]
for j in range(len(l1)-1):
    for i in range(len(l1)-1-j):
        if l1[i]>l1[i+1]:
            l1[i],l1[i+1]=l1[i+1],l1[i]
            print(l1)

[10, 4, 15, 23, 0]
[10, 4, 15, 0, 23]
[4, 10, 15, 0, 23]
[4, 10, 0, 15, 23]
[4, 0, 10, 15, 23]
[0, 4, 10, 15, 23]


In [15]:
l=[10,15,4,23,0]
for i in range(len(l)-1,0,-1):
    for j in range(i):
        if l[j]>l[j+1]:
            l[j+1],l[j]=l[j],l[j+1]
            print(l)

[10, 4, 15, 23, 0]
[10, 4, 15, 0, 23]
[4, 10, 15, 0, 23]
[4, 10, 0, 15, 23]
[4, 0, 10, 15, 23]
[0, 4, 10, 15, 23]


In [13]:
#insertion soring
l1=[10,4,25,1,5]
print(l1)
for i in range(1,len(l1)):
    for j in range(len(l1)-1):
        if l1[i]<l1[j]:
            temp=l1[i]
            l1[i]=l1[j]
            l1[j]=temp
            print(l1)

[10, 4, 25, 1, 5]
[4, 10, 25, 1, 5]
[4, 25, 10, 1, 5]
[4, 10, 25, 1, 5]
[1, 10, 25, 4, 5]
[1, 4, 25, 10, 5]
[1, 4, 10, 25, 5]
[1, 4, 5, 25, 10]
[1, 4, 5, 10, 25]


In [2]:
l=[15,6,13,22,3,52,2]
n=len(l)
for i in range(n):
    for j in range(0,n-i-1):
        print(j)

0
1
2
3
4
5
0
1
2
3
4
0
1
2
3
0
1
2
0
1
0


In [4]:
import numpy as np

# 2D ndarray
a = np.array([[1, 2, 3], [4, 5, 6]])
print("2D ndarray:")
print(a)

# 3D ndarray
b = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("3D ndarray:")
print(b)

2D ndarray:
[[1 2 3]
 [4 5 6]]
3D ndarray:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [15]:
t=np.transpose(a)
print(t)

[[1 4]
 [2 5]
 [3 6]]


In [16]:
t1=np.transpose(b)
print(t1)

[[[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]

 [[ 3  9]
  [ 6 12]]]


In [18]:
a.shape

(2, 3)

In [19]:
b.shape

(2, 2, 3)

In [20]:
a.itemsize

4

In [21]:
b.itemsize

4

In [1]:
for i in range(10):
    if i<=4:
        print(i)
        continue
    else:
        break

0
1
2
3
4


In [2]:
def updict(mydict):
    list(mydict.items())[0][1].update({list(list(mydict.items())[0][1].keys())[0]:"pjain"})
    print(mydict)
mydict={1:{2:"pj"}}
updict(mydict)

{1: {2: 'pjain'}}


In [3]:
3/2

1.5

In [2]:
3%2

1

In [11]:
63%6


3

In [1]:
print("Rudra")

Rudra


In [5]:

type(a)

tuple

In [1]:
a="Rudra"
print(a[1:])

udra


In [3]:
l1=[1,2,3,4,5,6,6,5,3,2]
l2=[]
for i in l1:
    if i not in l2:
        l2.append(i)
print(l2)

[1, 2, 3, 4, 5, 6]


In [6]:
# WAP to print 1st N prime num
def firt_prinme(N):
    count=0
    i=2
    while count<N:
        if is_prime(i):
            print(i,end=" ")
            count+=1
        i+=1
def is_prime(i):
    for j in range(2,i):
        if (i%j)==0:
            break
    else:
        return True
N=int(input())
firt_prinme(N)

2 3 5 7 11 13 17 19 23 29 

In [1]:
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

def print_first_n_primes(n):
    count = 0
    i = 2
    while count < n:
        if is_prime(i):
            print(i, end=", ")
            count += 1
        i += 1

# Example usage:
print_first_n_primes(10)

2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 

In [12]:
def n_p():
    c=1+2
    return c
n_p()

3

In [13]:
def n_p():
    c=1+2
    print(c)
n_p()

3


In [1]:
X,Y,Z=map(int,input().split())
print((X-Y)+Z)

4


In [1]:
l1=[1,2,3,4,5]
print(l1[::-1])

[5, 4, 3, 2, 1]


In [2]:
a="Rudra"


R


In [1]:
i=1
while True:
    if i%3==0:
        break
    print(i)
    i+=1

1
2


In [2]:
def fact(n):
    if n==0:
        return 1
    return n * fact(n-1) 
print(fact(5))

120


In [3]:
5%2

1

In [2]:
10//2

5

In [2]:
a="23"
print(a[1])

3


In [1]:
n=int(input("ENter a number: "))
count=0
for i in range(n):
    if i%2==0:
        count+=i
print(count)

2


In [9]:
n=int(input("ENter a number: "))
sum=0
num=1
while num<=n:
    if num%2==0:
        sum+=num
    num+=1
print(sum)

6


In [7]:
word=input("Enter the word to be reversed: ")
l1=[]
l1=word.split()
print(l1)
l1[0],l1[-1]=l1[-1],l1[0]
print(l1)

['Rudra']
['Rudra']


In [ ]:
for i in range(0,6):
    for j in range(0,j):
        if i