In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [4]:
arr.ndim

1

In [5]:
arr2=np.array([[1,2],[3,4]])
arr2

array([[1, 2],
       [3, 4]])

In [6]:
arr2.ndim

2

In [7]:
arr=np.array([1,2,3,4], ndmin=2,dtype=float)
arr

array([[1., 2., 3., 4.]])

In [7]:
np.arange(10,22,2)

array([10, 12, 14, 16, 18, 20])

In [5]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [28]:
np.empty((2,2))

array([[6.23042070e-307, 4.67296746e-307],
       [1.69121096e-306, 1.04433753e-311]])

In [19]:
np.empty((3,3,3))

array([[[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
        [8.90108992e-307, 1.89146896e-307, 7.56571288e-307],
        [3.11525958e-307, 1.24610723e-306, 1.37962320e-306]],

       [[1.29060871e-306, 2.22518251e-306, 1.33511969e-306],
        [1.78022342e-306, 1.05700345e-307, 3.11525958e-307],
        [1.69118108e-306, 8.06632139e-308, 1.20160711e-306]],

       [[1.69119330e-306, 1.29062229e-306, 1.60217812e-306],
        [1.37961370e-306, 1.42417629e-306, 1.24611402e-306],
        [2.22522596e-306, 8.34445562e-308, 1.92038816e+243]]])

In [12]:
np.empty((2,2))

array([[1., 2.],
       [3., 4.]])

In [13]:
np.empty((5,2))

array([[6.23042070e-307, 4.67296746e-307],
       [1.69121096e-306, 8.90108992e-307],
       [1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306],
       [1.29061142e-306, 5.53353523e-322]])

In [14]:
import random

In [30]:
np.random.randint(50,75,(2,2))

array([[53, 55],
       [70, 57]])

In [16]:
np.random.randn(2,2)

array([[-0.36364873,  1.09244932],
       [ 0.69857548,  0.39141849]])

In [36]:
np.eye(2,4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0]])

In [38]:
np.zeros((4,4,3),dtype=int)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

Experiment 2

In [19]:
d1_array=np.array([12,15,20,155])
d1_array

array([ 12,  15,  20, 155])

In [20]:
d1_array.ndim

1

In [21]:
d1_array.T

array([ 12,  15,  20, 155])

In [22]:
d1_array.shape

(4,)

In [23]:
d1_array.itemsize

4

In [24]:
d1_array.size

4

In [25]:
d1_array.dtype

dtype('int32')

In [26]:
d1_array.real

array([ 12,  15,  20, 155])

In [27]:
d1_array.imag

array([0, 0, 0, 0])

In [28]:
d2_array=np.array([[15.2,20.3,16.2],[18.2,17.03,11.033],[16.03,9.08,7.033]])
d2_array

array([[15.2  , 20.3  , 16.2  ],
       [18.2  , 17.03 , 11.033],
       [16.03 ,  9.08 ,  7.033]])

In [29]:
d2_array.size

9

In [30]:
d2_array.itemsize

8

In [31]:
d2_array.ndim

2

In [32]:
d2_array.T

array([[15.2  , 18.2  , 16.03 ],
       [20.3  , 17.03 ,  9.08 ],
       [16.2  , 11.033,  7.033]])

In [33]:
d2_array.dtype

dtype('float64')

In [34]:
d2_array.shape

(3, 3)

In [35]:
d2_array.real

array([[15.2  , 20.3  , 16.2  ],
       [18.2  , 17.03 , 11.033],
       [16.03 ,  9.08 ,  7.033]])

In [36]:
d2_array.imag

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
d3_array=np.array([[[2,3,4],[5,6,7],[8,9,10]],[[11,12,13],[14,15,16],[17,18,19]],[[20,21,22],[23,24,25],[26,27,28]]])
d3_array

array([[[ 2,  3,  4],
        [ 5,  6,  7],
        [ 8,  9, 10]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]],

       [[20, 21, 22],
        [23, 24, 25],
        [26, 27, 28]]])

In [38]:
d3_array.ndim

3

In [39]:
d3_array.T

array([[[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]],

       [[ 3, 12, 21],
        [ 6, 15, 24],
        [ 9, 18, 27]],

       [[ 4, 13, 22],
        [ 7, 16, 25],
        [10, 19, 28]]])

In [40]:
d3_array.size

27

In [41]:
d3_array.itemsize

4

In [42]:
d3_array.shape

(3, 3, 3)

In [43]:
d3_array.dtype

dtype('int32')

In [44]:
d3_array.imag

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [45]:
d2_array.real

array([[15.2  , 20.3  , 16.2  ],
       [18.2  , 17.03 , 11.033],
       [16.03 ,  9.08 ,  7.033]])

Experiment 3

In [46]:
np.arange(10,20,2,dtype=int)


array([10, 12, 14, 16, 18])

In [47]:
np.empty((3,3),dtype=int)

array([[4128860, 6029375, 3801155],
       [5570652, 6619251, 7536754],
       [5374044, 6553717, 6357106]])

In [48]:
np.linspace(1,10,5,dtype=float)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [49]:
np.random.randint(2,10)

8

In [50]:
np.random.randint(0,10,(3,3))

array([[3, 7, 8],
       [0, 1, 9],
       [3, 7, 4]])

In [51]:
np.random.randn(3,3)

array([[ 0.31978161, -0.93719144, -1.0603114 ],
       [-0.18615888,  0.66680132,  0.57710226],
       [ 0.23852777,  0.46268596,  0.41110233]])

In [7]:
np.zeros((3,3),dtype="int")

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

Experiment 4

In [53]:
q1_arr= np.arange(0,120,1,dtype="int")
q1_arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119])

In [54]:
q1_arr2=q1_arr.reshape(3,4,10)
q1_arr2

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39]],

       [[ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79]],

       [[ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
        [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114, 115, 116, 117, 118, 119]]])

In [55]:
q1_arr2.shape

(3, 4, 10)

In [56]:
q1_arr2.size

120

In [41]:
q2_arr= np.arange(0,100,1,dtype="int")
q2_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [45]:
q2_arr.resize(2,5,6)
q2_arr

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29]],

       [[ 0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0]]])

Experiment 5

In [59]:
capacity=np.array([1,7,13,105,10,100])
capacity

array([  1,   7,  13, 105,  10, 100])

In [60]:
capacity.size

6

In [61]:
capacity.itemsize*capacity.size

24

In [62]:
l1=[1,2,3,4,5]
speed=np.array(l1)
speed

array([1, 2, 3, 4, 5])

In [63]:
l2=speed.tolist()

In [64]:
l1==l2

True

In [52]:
orignal=np.arange(1,2,0.1,dtype=float)
orignal

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [53]:
np.zeros_like(orignal)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Experiment 6

Performing indexing on nd array.

consider the following numpy array and return following array elements
[10.5,13.5,17.5,199.5,85.5]
199.5 positive and negative 

In [67]:
arr=np.array([10.5,13.5,17.5,199.5,85.5])
print(arr[3])
print(arr[-2])

199.5
199.5


11 22 33
44 55 66
71 88 99
return second row

In [4]:
arr=np.array([[11, 22, 33],[44, 55, 66],[77,88,99]])
print(arr[1])

[44 55 66]


create 
11 22
33 44 

55 66
77 88

return 11,66,second plane
11,44,55,88 using advance

In [5]:
arr=np.array([[[11,22],[33,44]],[[55,66],[77,88]]])
print(arr[0,0,0])
print(arr[1,0,1])
print(arr[1])
print(arr[[0,0,1,1],[0,1,0,1],[0,1,0,1]])

11
66
[[55 66]
 [77 88]]
[11 44 55 88]


100 201 301 401
501 601 701 801
901 1001 2001 3001

return 201,701,401,3001 using advance

In [8]:
arr=np.array([[100,201,301,401],[501,601,701,801],[901,1001,2001,3001]])
arr
print(arr[[0,1,0,2],[1,2,3,3]])

[ 201  701  401 3001]


Experiment 7

1) create a numpy arrayb of 15 element using arange function and resahpe it into 5x3
--> return all rows but only 1st and 2nd coloumn elements
--> return 7,8,10,11

In [18]:
arr=np.arange(15)
print("Array: ","\n",arr,"\n")
arr=arr.reshape(5,3)
print("Updated Array: ","\n",arr,"\n")
print("All roes with 1st and 2nd column: ","\n",arr[:,1:3],"\n")
print(arr[2:4,1:3])

Array:  
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] 

Updated Array:  
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]] 

All roes with 1st and 2nd column:  
 [[ 1  2]
 [ 4  5]
 [ 7  8]
 [10 11]
 [13 14]] 

[[ 7  8]
 [10 11]]


2)  consider following numpy array
    [[3,6,9,12],
    [15,18,21,24],
    [27,30,33,36],
    [39,42,45,48],
    [52,54,57,60]]

return a sub array consisting of odd rows and even coloumns of array

In [72]:
arr=np.array([[3,6,9,12],[15,18,21,24],[27,30,33,36],[39,42,45,48],[52,54,57,60]])
print("Array: ","\n",arr,"\n")
print("Odd Rows and Even Columns: ","\n",arr[1:4:2,0:3:2])

Array:  
 [[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [52 54 57 60]] 

Odd Rows and Even Columns:  
 [[15 21]
 [39 45]]


3) Consider the 3D array [[[67,49],[35,32],[31,29]],[[18,9],[12,24],[61,63]]]
return 67,49,35,32,18,9,12,24 using positive an d negative indexing

In [73]:
arr=np.array([[[67,49],[35,32],[31,29]],[[18,9],[12,24],[61,63]]])
print("Array: ","\n",arr,"\n")
print("Using Positive Indexing: ","\n",arr[:,0:2,:],"\n")
print("Using Negative Indexing","\n",arr[:,-3:-1,:])

Array:  
 [[[67 49]
  [35 32]
  [31 29]]

 [[18  9]
  [12 24]
  [61 63]]] 

Using Positive Indexing:  
 [[[67 49]
  [35 32]]

 [[18  9]
  [12 24]]] 

Using Negative Indexing 
 [[[67 49]
  [35 32]]

 [[18  9]
  [12 24]]]


In [74]:
l1=[0,5,3,7]
print(l1[3:4])

[7]


In [75]:
l1=[0,5,3,7]
print(l1[-1])

7


Experiment 8
 Converting nd array in one dimenseion using ravel() and fatten() method

In [76]:
#Converting anarray in one dimension using Ravel and flatten().
#create an ndarray of shape 3x5 and flatten that array using ravel and flatten method.
#Write a programe to clarify the difference between ravel and flatten method.
#Proof that ravel takes less that time as compare to flatten method.

In [77]:
a=np.array([(11,22,33,44),(55,66,77,88)])
print("Original Array: ",a)
b=a.flatten()
c=np.ravel(a)
print("Flatten array usinf flatten methode: ",b)
print("Flatten array usinng ravel methode: ",c)

Original Array:  [[11 22 33 44]
 [55 66 77 88]]
Flatten array usinf flatten methode:  [11 22 33 44 55 66 77 88]
Flatten array usinng ravel methode:  [11 22 33 44 55 66 77 88]


In [78]:
a=np.random.randint(50,75,(3,5))
print("Original Array: ",a)
b=a.flatten()
c=np.ravel(a)
print("Flatten array using flatten methode:",b)
print("Flatten array using ravel methode: ",c)

Original Array:  [[73 56 58 59 66]
 [68 51 51 66 63]
 [72 71 66 61 64]]
Flatten array using flatten methode: [73 56 58 59 66 68 51 51 66 63 72 71 66 61 64]
Flatten array using ravel methode:  [73 56 58 59 66 68 51 51 66 63 72 71 66 61 64]


In [19]:
arr1=np.random.randint(12,56,(3,3))
print("Orignal Array:\n",arr1)
#flatten
arr2=arr1.flatten()
print("Flatten array using flatten methode: ",arr2)
arr2[4]=0
print("updated flatten array: ",arr2)
print("Orignal array after update:\n",arr1)
#ravel
arr2=arr1.ravel()
print("Flatten array using flatten methode: ",arr2)
arr2[4]=0
print("updated flatten array: ",arr2)
print("Orignal array after update:\n",arr1)


Orignal Array:
 [[55 34 47]
 [26 21 49]
 [14 55 46]]
Flatten array using flatten methode:  [55 34 47 26 21 49 14 55 46]
updated flatten array:  [55 34 47 26  0 49 14 55 46]
Orignal array after update:
 [[55 34 47]
 [26 21 49]
 [14 55 46]]
Flatten array using flatten methode:  [55 34 47 26 21 49 14 55 46]
updated flatten array:  [55 34 47 26  0 49 14 55 46]
Orignal array after update:
 [[55 34 47]
 [26  0 49]
 [14 55 46]]


In [80]:
arr=np.arange(9).reshape(3,3)


In [81]:
%%timeit
arr.ravel()

134 ns ± 16.7 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [82]:
%%timeit
arr.flatten()


845 ns ± 55.1 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


Experiment 9 Joining two array using concatenate()

In [83]:
#write a numpy program to concatenate 2 2d array
#Write a numpy program to concatenate 2 2d array by axix 0 and 1.
#create a list of 10 2d array of shape 3*4 and join the using the stack function use axix 0,1,2
#create any 2d array of same shape amd perform hstack vstack and dstack.
#create any 3d array of same shape amd perform hstack vstack and dstack.

In [84]:
arr1=np.array([[0,1,3],[5,7,9]])
arr2=np.array([[0,2,4],[6,8,10]])
np.concatenate((arr1,arr2))

array([[ 0,  1,  3],
       [ 5,  7,  9],
       [ 0,  2,  4],
       [ 6,  8, 10]])

In [66]:
arr1=np.array([[5,4],[6,8]])
arr2=np.array([[13,5],[72,9]])
print("Axix=0")
a=np.concatenate((arr1,arr2),axis=0)
print(a)
print("Axix=1")
b=np.concatenate((arr1,arr2),axis=1)
print(b)
a7=np.vstack((arr1,arr2))
print("Using vstack: ")
print(a7)

Axix=0
[[ 5  4]
 [ 6  8]
 [13  5]
 [72  9]]
Axix=1
[[ 5  4 13  5]
 [ 6  8 72  9]]
Using vstack: 
[[ 5  4]
 [ 6  8]
 [13  5]
 [72  9]]


In [64]:
l1=[]
for i in range(10):
    a=np.random.randint(10,100,(3,4))
    l1.append(a)
print(l1)
stk=np.stack((l1),axis=0)
print(stk)

stk1=np.stack((l1),axis=1)
print(stk1)

stk2=np.stack((l1),axis=2)
print(stk2)

[array([[76, 60, 78, 98],
       [23, 14, 84, 44],
       [46, 54, 44, 37]]), array([[56, 99, 15, 64],
       [35, 22, 37, 81],
       [25, 97, 69, 18]]), array([[55, 16, 11, 67],
       [84, 44, 79, 37],
       [67, 62, 33, 31]]), array([[72, 18, 56, 95],
       [65, 98, 51, 69],
       [47, 83, 86, 76]]), array([[49, 34, 23, 67],
       [33, 39, 10, 71],
       [41, 73, 90, 46]]), array([[20, 93, 44, 71],
       [34, 30, 75, 52],
       [83, 64, 41, 70]]), array([[68, 63, 59, 77],
       [21, 36, 58, 76],
       [30, 80, 82, 84]]), array([[94, 87, 41, 23],
       [95, 17, 50, 86],
       [28, 32, 73, 48]]), array([[68, 67, 58, 63],
       [33, 44, 57, 62],
       [19, 72, 58, 15]]), array([[39, 72, 86, 17],
       [15, 10, 74, 89],
       [97, 95, 22, 54]])]
[[[76 60 78 98]
  [23 14 84 44]
  [46 54 44 37]]

 [[56 99 15 64]
  [35 22 37 81]
  [25 97 69 18]]

 [[55 16 11 67]
  [84 44 79 37]
  [67 62 33 31]]

 [[72 18 56 95]
  [65 98 51 69]
  [47 83 86 76]]

 [[49 34 23 67]
  [33 39 10 7

In [60]:
arr5=np.array([[1,3,4],[5,7,9]])
print(arr5)
arr6=np.array([[5,8,0],[2,5,8]])
print(arr6)
a1=np.vstack((arr5,arr6))
print("Using vstack: ")
print(a1)
a2=np.hstack((arr5,arr6))
print("Using hstack: ")
print(a2)
a3=np.dstack((arr5,arr6))
print("Using dstack: ")
print(a3)


[[1 3 4]
 [5 7 9]]
[[5 8 0]
 [2 5 8]]
Using vstack: 
[[1 3 4]
 [5 7 9]
 [5 8 0]
 [2 5 8]]
Using hstack: 
[[1 3 4 5 8 0]
 [5 7 9 2 5 8]]
Using dstack: 
[[[1 5]
  [3 8]
  [4 0]]

 [[5 2]
  [7 5]
  [9 8]]]


In [67]:
arr8=np.array([[[1,3,4],[5,7,9],[6,3,8]]])
print(arr8)
arr9=np.array([[[5,8,0],[2,5,8],[8,5,2]]])
print(arr9)
a7=np.vstack((arr8,arr9))
print("Using vstack: ")
print(a7)
a8=np.hstack((arr8,arr9))
print("Using hstack: ")
print(a8)
a9=np.dstack((arr8,arr9))



[[[1 3 4]
  [5 7 9]
  [6 3 8]]]
[[[5 8 0]
  [2 5 8]
  [8 5 2]]]
Using vstack: 
[[[1 3 4]
  [5 7 9]
  [6 3 8]]

 [[5 8 0]
  [2 5 8]
  [8 5 2]]]
Using hstack: 
[[[1 3 4]
  [5 7 9]
  [6 3 8]
  [5 8 0]
  [2 5 8]
  [8 5 2]]]
Using dstack: 
[[[1 3 4 5 8 0]
  [5 7 9 2 5 8]
  [6 3 8 8 5 2]]]


Experiment 10 Spliting of nd arrays. 

In [ ]:
#To split an array of 15 elements into 3 sub arrays.
#Write a numoy program to create an nd array of size 8x3 from the range between 10 to 34 then 10 to 34 then split the array into 4 equal size sub array. 
#Write a numpy program to split an array of shape 4x4 into 2 along the 2 axis(hsplit methode)
#Create a array of 27 elements and reshape it into 3x3x3 and split that array depth wise(dsplit)
#Write a python progarm to create an array of 10 elements and split the array using split methode as well as array_split methode and write down the difference between both the methode.

In [2]:
import numpy as np

In [7]:
arr=np.array([1,2,3,4,5,6,7,8,9,0,12,23,45,67,89])
np.split(arr,3)

[array([1, 2, 3, 4, 5]), array([6, 7, 8, 9, 0]), array([12, 23, 45, 67, 89])]

In [68]:
arr=np.random.randint(10,34,(8,3))
print(arr)
np.split(arr,4)

[[20 17 26]
 [11 27 10]
 [27 18 22]
 [17 18 12]
 [21 11 22]
 [22 31 22]
 [19 20 12]
 [29 17 24]]


[array([[20, 17, 26],
        [11, 27, 10]]),
 array([[27, 18, 22],
        [17, 18, 12]]),
 array([[21, 11, 22],
        [22, 31, 22]]),
 array([[19, 20, 12],
        [29, 17, 24]])]

In [70]:
arr=np.random.randint(10,34,(4,4))
print(arr)
np.hsplit(arr,2)

[[24 30 19 22]
 [20 12 21 19]
 [11 33 22 33]
 [25 19 23 14]]


[array([[24, 30],
        [20, 12],
        [11, 33],
        [25, 19]]),
 array([[19, 22],
        [21, 19],
        [22, 33],
        [23, 14]])]

In [69]:
arr=np.arange(27)
a=arr.reshape(3,3,3)
print(a)
np.dsplit(a,3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


[array([[[ 0],
         [ 3],
         [ 6]],
 
        [[ 9],
         [12],
         [15]],
 
        [[18],
         [21],
         [24]]]),
 array([[[ 1],
         [ 4],
         [ 7]],
 
        [[10],
         [13],
         [16]],
 
        [[19],
         [22],
         [25]]]),
 array([[[ 2],
         [ 5],
         [ 8]],
 
        [[11],
         [14],
         [17]],
 
        [[20],
         [23],
         [26]]])]

In [72]:
ar=np.arange(10)
np.split(ar,2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [3]:
ar=np.arange(10)
np.array_split(ar,3)

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

Practicals

In [30]:
rand_arr=np.random.randint(1,20,(4,5))
print("2D array with random elements:\n",rand_arr)
print("Required elements using basic indexing: ")
print(rand_arr[0,0],rand_arr[0,2],rand_arr[1,0],rand_arr[1,1],rand_arr[1,3],rand_arr[2,1])
print("Required elements using advance indexing: ")
print(rand_arr[0][0])

2D array with random elements:
 [[11  7 19 18 18]
 [15  6 11 10  6]
 [16  3 19  1 19]
 [ 2  2  4  7  6]]
Required elements using basic indexing: 
11 19 15 6 10 3
Required elements using advance indexing: 


In [35]:
new_arr=np.random.randint(0,20,(3,5))
print("Required array of shape 3x5:\n",new_arr)
flatten_array=new_arr.flatten()
print("Flattened array using flatten()",flatten_array)
ravel_array=np.ravel(new_arr)
print("Flattened array using ravel()",ravel_array)

Required array of shape 3x5:
 [[11  3 12  0 17]
 [ 1  5  0  8 10]
 [ 3 11  4  2 19]]
Flattened array using flatten() [11  3 12  0 17  1  5  0  8 10  3 11  4  2 19]
Flattened array using ravel() [11  3 12  0 17  1  5  0  8 10  3 11  4  2 19]


In [51]:
num_arr=np.array([1,17,113,105])
print("Array: ",num_arr)
size=(num_arr.size*num_arr.itemsize)
print("Size of array: ",size)

Array:  [  1  17 113 105]
Size of array:  16
